# helper file
library(extrafont)
windowsFonts(Times=windowsFont("Times New Roman"))
library(tidyverse)
library(FNGr)
library(broom)
library(gridExtra)
library(cowplot)
# library(lme4)
# library(FSA)
# library(RFishBC)
library(magrittr)
# library(stringr)
# library(arm)
# library(nlme)
# library(multcomp)
# library(FinCal)
# library(msmtools)
# library(psych)
# library(WRS2)
# library(cowplot)


theme_set(theme_sleek())